version: '3.7'

networks:
  network:

services:

  db:
    container_name: db_$APP_NAME
    image: mysql:5.7
    restart: always
    ports:
      - $MYSQL_EXT_PORT:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin_$APP_NAME
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "8011:80"
    restart: always   
    networks:
      - network
    
  wordpress:
    container_name: wp_$APP_NAME
    depends_on:
      - db
    build: wordpress/.
    restart: always
    ports:
      - $WORDPRESS_EXT_PORT:80
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

volumes:
  wordpress:
  db: